services:
  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - rt

  app:
    build: .
    env_file:
      - .env
    ports:
      - 5000:5000
    networks:
      - rt

networks:
  rt:
